[package]
name = "reflect_macros"
version = "0.1.0"
edition = "2021"


[lib]
path = "src/lib.rs"
proc-macro = true


[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
once_cell = "1.19.0"
